id: A10D8F129
title: CV_Verses 41-60
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:11:00.583821
  last_modified_at: 2022-03-01 23:11:00.583824
