id: A10D8F129
title: CI_Verses 1-20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:11:00.542770
  last_modified_at: 2022-03-01 23:11:00.542776
