id: A10D8F129
title: CIV_Verses 81-100
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:11:00.536477
  last_modified_at: 2022-03-01 23:11:00.536480
