id: A10D8F129
title: CI_Verses 61-80
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:11:00.561015
  last_modified_at: 2022-03-01 23:11:00.561020
